# Book settings
title: PHYS 1801
author: Firas Moosvi
logo: images/emwaves.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]

latex:
  latex_documents:
    targetname: book.tex
html:
  navbar_number_sections: false
  home_page_in_navbar: true
  baseurl: "https://firas.moosvi.com/interviews/york_physics/" # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false
  extra_footer: |
    <div>
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
        All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
    </div>

launch_buttons:
  thebe: false

bibtex_bibfiles:
  - bibliography.bib

sphinx:
  # extra_extensions:
  #   - jupyterlite_sphinx
  config:
    html_show_copyright: false
    html_extra_path: ["files","images"]
    myst_enable_extensions:
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_admonition
      - html_image
      - linkify
      - replacements
      - smartquotes
      - substitution
    myst_substitutions:
      COURSE_CODE: "Physics 1801"
      TITLE: "Electricity, Magnetism, and Optics for Engineers"
      PREREQS: "PHYS 1800, MATH 1013"
      COREQS: "MATH 1014 or MATH 1310 or MATH 1505"
      TERM: "2022 Winter Term 2"
      ROOM: "Online Via Zoom"
      MEETING_TIMES: "Monday, Wednesday, Friday from 10-11 AM"
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "11:59 PDT on September 20, 2022"
      W_DATE_2: "11:59 PDT on November 12, 2022"
      W_DATE_3: "November 12, 2022"
      EXAM_PERIOD: "Saturday December 11th - Wednesday, December 22"
      CANVAS_ID: "00000"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID" # {{ '[course website]({link})'.format(link=CANVAS_LINK.replace('CANVAS_ID',CANVAS_ID)) }}
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      ANNOUNCEMENTS_LINK: "[Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/2021_WT1/physics111"
      FORUM_LINK: "Ed Discussion"
      #FORUM_LINK: "[Ed Discussion (sign up for it here)](https://ubc.ca1.qualtrics.com/jfe/form/SV_1BTAIXiMPvBRR2K)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410)"
      FORMAT: "Lectures, Labs, Tutorials will all be running online in this course."
      ASSOCIATE_HEAD: "Jake Bobowski [jake.bobowski@ubc.ca](mailto:jake.bobowski@ubc.ca)"
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/jfe/form/SV_doJPm2LTfr463Fb)"
