name: deploy-book

# Only run this when the master branch changes
on:
  workflow_dispatch:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: cache installation
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        
#     - name: Setup tmate session
#       env:
#         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#         REMOTE_USER: ${{ secrets.REMOTE_USER }}
#         REMOTE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#         REMOTE_DIR: ${{ secrets.REMOTE_TARGET }}
#         LOCAL_DIR: "_build/html/"
#       uses: mxschmitt/action-tmate@v3
#       timeout-minutes: 15
      
    # Push to server
    - name: rsync and ssh
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_DIR: ${{ secrets.REMOTE_TARGET }}
        LOCAL_DIR: "_build/html/"
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/id_rsa
        echo "$REMOTE_KEY" > ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        pwd
        ls -la
        rsync -avzr --delete _build/html/ $REMOTE_USER@$REMOTE_HOST:firas.moosvi.com/interviews/sfu_talk
        
